#!/bin/sh
#
# This file is automatically generated from the .gitignore file.
# CHANGES TO THIS FILE WILL BE DISCARDED!

zip -9 -r ../code.zip .\
 -x '.gitignore' \
 -x '.git/*' \
 -x 'venv/*' \
 -x '.venv/*' \
 -x '.git.old/*' \
 -x '*__pycache__/*' \
 -x 'tests/*' \
 -x '.vscode/*' \
 -x 'fr5_description/*' -x 'test.py' -x 'env.py' -x 'README.md' -x 'image.png' -x 'requirements.txt'